"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p^%na^geh=4@-eh@!+p9ol^=gcamp#n)bw=k$lkcpkx*e#%zj9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',  # JNext API 앱
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Firebase Admin SDK 초기화
import firebase_admin
from firebase_admin import credentials, firestore

# Firebase 서비스 계정 키 경로 (환경변수 또는 기본값)
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH', 'jnext-service-account.json')

# JNext 루트 또는 backend 폴더에서 서비스 계정 키 찾기
if not os.path.isabs(FIREBASE_CREDENTIALS_PATH):
    # 상대 경로인 경우, JNext 루트 먼저 확인
    jnext_root_path = BASE_DIR.parent / FIREBASE_CREDENTIALS_PATH
    backend_path = BASE_DIR / FIREBASE_CREDENTIALS_PATH
    
    if jnext_root_path.exists():
        firebase_cred_path = jnext_root_path
    elif backend_path.exists():
        firebase_cred_path = backend_path
    else:
        firebase_cred_path = jnext_root_path  # 기본값 (에러 메시지용)
else:
    firebase_cred_path = Path(FIREBASE_CREDENTIALS_PATH)

# Firebase 초기화 (이미 초기화되어 있지 않은 경우에만)
FIREBASE_INITIALIZED = False
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate(str(firebase_cred_path))
        firebase_admin.initialize_app(cred)
        FIREBASE_INITIALIZED = True
        print(f"[JNext] Firebase initialized successfully")
        print(f"[JNext] Credentials loaded from: {firebase_cred_path}")
    except Exception as e:
        print(f"[JNext] Firebase initialization failed: {e}")
        print(f"[JNext] Please ensure the service account key exists at:")
        print(f"  - {BASE_DIR.parent / 'jnext-service-account.json'} (JNext root)")
        print(f"  - {BASE_DIR / 'jnext-service-account.json'} (backend folder)")
        print(f"[JNext] Server will start without Firebase support.")

# Firestore 클라이언트 인스턴스 (Firebase 초기화 성공 시에만 생성)
db = None
if FIREBASE_INITIALIZED:
    try:
        db = firestore.client()
    except Exception as e:
        print(f"[JNext] Failed to create Firestore client: {e}")
