"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# .env 파일 로드
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p^%na^geh=4@-eh@!+p9ol^=gcamp#n)bw=k$lkcpkx*e#%zj9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 개발용: 모든 호스트 허용


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',  # JNext API 앱
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static 파일 서빙
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Phase 5: 템플릿 경로 추가
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Phase 5: static 폴더 추가
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic 수집 경로

# Whitenoise 설정 (Render용)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Firebase Admin SDK 초기화
import firebase_admin
from firebase_admin import credentials, firestore

# Firebase 서비스 계정 키 경로 (환경변수 또는 기본값)
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH', 'jnext-service-account.json')

# JNext 루트 또는 backend 폴더에서 서비스 계정 키 찾기
if not os.path.isabs(FIREBASE_CREDENTIALS_PATH):
    # 상대 경로인 경우, JNext 루트 먼저 확인
    jnext_root_path = BASE_DIR.parent / FIREBASE_CREDENTIALS_PATH
    backend_path = BASE_DIR / FIREBASE_CREDENTIALS_PATH
    
    if jnext_root_path.exists():
        firebase_cred_path = jnext_root_path
    elif backend_path.exists():
        firebase_cred_path = backend_path
    else:
        firebase_cred_path = jnext_root_path  # 기본값 (에러 메시지용)
else:
    firebase_cred_path = Path(FIREBASE_CREDENTIALS_PATH)

# Firebase 초기화 (이미 초기화되어 있지 않은 경우에만)
FIREBASE_INITIALIZED = False
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate(str(firebase_cred_path))
        firebase_admin.initialize_app(cred)
        FIREBASE_INITIALIZED = True
        print(f"[JNext] Firebase initialized successfully")
        print(f"[JNext] Credentials loaded from: {firebase_cred_path}")
    except Exception as e:
        print(f"[JNext] Firebase initialization failed: {e}")
        print(f"[JNext] Please ensure the service account key exists at:")
        print(f"  - {BASE_DIR.parent / 'jnext-service-account.json'} (JNext root)")
        print(f"  - {BASE_DIR / 'jnext-service-account.json'} (backend folder)")
        print(f"[JNext] Server will start without Firebase support.")

# Firestore 클라이언트 인스턴스 (Firebase 초기화 성공 시에만 생성)
db = None
if FIREBASE_INITIALIZED:
    try:
        db = firestore.client()
    except Exception as e:
        print(f"[JNext] Failed to create Firestore client: {e}")

# API Key 설정 (Phase 2: 보안)
JNEXT_API_KEY = os.getenv('JNEXT_API_KEY', None)
if JNEXT_API_KEY:
    print(f"[JNext] API Key authentication enabled")
else:
    print(f"[JNext] API Key authentication disabled (development mode)")

# ============================================================
# Phase 3 & 4: AI 멀티 모델 설정 (Gemini, GPT, Claude)
# ============================================================

# Gemini 설정
from google import genai

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', None)
GEMINI_INITIALIZED = False
GEMINI_CLIENT = None

if GEMINI_API_KEY:
    try:
        print(f"[JNext] Using Gemini API Key: {GEMINI_API_KEY[:20]}...")
        GEMINI_CLIENT = genai.Client(api_key=GEMINI_API_KEY)
        GEMINI_INITIALIZED = True
        print(f"[JNext] Gemini AI initialized successfully (google.genai)")
    except Exception as e:
        print(f"[JNext] Gemini initialization failed: {e}")
else:
    print(f"[JNext] Gemini API Key not found in .env")

# GPT 설정
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', None)
GPT_CLIENT = None
GPT_INITIALIZED = False

if OPENAI_API_KEY:
    try:
        import openai
        GPT_CLIENT = openai.OpenAI(api_key=OPENAI_API_KEY)
        GPT_INITIALIZED = True
        print(f"[JNext] GPT initialized successfully")
    except Exception as e:
        print(f"[JNext] GPT initialization failed: {e}")
else:
    print(f"[JNext] GPT API Key not found in .env")

# Claude 설정
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', None)
CLAUDE_CLIENT = None
CLAUDE_INITIALIZED = False

if ANTHROPIC_API_KEY:
    try:
        import anthropic
        CLAUDE_CLIENT = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
        CLAUDE_INITIALIZED = True
        print(f"[JNext] Claude initialized successfully")
    except Exception as e:
        print(f"[JNext] Claude initialization failed: {e}")
else:
    print(f"[JNext] Claude API Key not found in .env")

# 모델 설정 (멀티 모델 지원)
AI_MODELS = {
    'gemini-flash': {
        'enabled': GEMINI_INITIALIZED,
        'model': 'models/gemini-2.5-flash',
        'client': GEMINI_CLIENT,
        'strengths': ['속도', '코스트', '한글'],
        'display_name': 'Gemini Flash (빠름)',
    },
    'gemini-pro': {
        'enabled': GEMINI_INITIALIZED,
        'model': 'models/gemini-2.5-pro',  # Gemini 2.5 Pro
        'client': GEMINI_CLIENT,
        'strengths': ['정확성', '추론', '분석'],
        'display_name': 'Gemini Pro (정확)',
    },
    'gpt': {
        'enabled': GPT_INITIALIZED,
        'model': 'gpt-5.2',
        'client': GPT_CLIENT,
        'strengths': ['창의성', '추론', '코딩'],
        'display_name': 'GPT-5.2 (진)',
    },
    'claude': {
        'enabled': CLAUDE_INITIALIZED,
        'model': 'claude-3-5-sonnet-20241022',
        'client': CLAUDE_CLIENT,
        'strengths': ['코딩', '분석', '논리'],
        'display_name': 'Claude Sonnet (코드왕)',
    }
}

# 기본 모델 (하이노밸런스는 Pro)
DEFAULT_AI_MODEL = 'gemini-pro'

# ============================================================
# JNext 컬렉션 구조 (3단계) - Hierarchical Structure
# ============================================================
COLLECTION_RAW = "raw"      # RAW: 원본/아이디어 (projects/{project_id}/raw)
COLLECTION_DRAFT = "draft"  # DRAFT: 정리 중 (projects/{project_id}/draft)
COLLECTION_FINAL = "final"  # FINAL: 최종 배포 (projects/{project_id}/final)

# Firestore 필드 스키마 (한글 필드명)
DOCUMENT_FIELDS = {
    # 기본 필드
    "제목": "str",
    "카테고리": "str",       # 하이노워킹, 하이노스케이팅 등
    "운동명": "str",         # 하이노워킹 패스트 등
    "내용": "str",           # 요약본
    "전체글": "str",         # 출판용 전체 글
    "작성일시": "timestamp",
    "수정일시": "timestamp",
    "작성자": "str",
    "데이터상태": "str",     # RAW | DRAFT | FINAL
    "종류": "str",           # 이론 | 실습 | 정리
    
    # 밈 관련 필드 (2026-01-10 추가)
    "밈이미지URL": "str",           # 원본 캐릭터 이미지 파일명
    "밈자막상단": "str",            # 상단 자막 텍스트
    "밈자막하단": "str",            # 하단 자막 텍스트
    "밈합성이미지URL": "str",       # 자막 합성된 최종 이미지
    "밈생성모델": "str",            # 진 (시트콤 캐릭터 + Pillow 합성)
    "밈스타일": "str",              # 시트콤, 일상 등
    "밈캐릭터": "str",              # 지피, 아내
}

# ============================================================
# Phase 4-3: AI 응답 스키마 (JSON 강제 - 환각 방지)
# ============================================================
AI_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "answer": {
            "type": "string",
            "description": "J님에게 보여줄 최종 답변"
        },
        "claims": {
            "type": "array",
            "items": {"type": "string"},
            "description": "핵심 주장 리스트"
        },
        "evidence": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "claim": {"type": "string"},
                    "collection": {"type": "string"},
                    "doc_id": {"type": "string"},
                    "field": {"type": "string"},
                    "value": {"type": "string"}
                },
                "required": ["claim", "collection"]
            },
            "description": "각 주장의 근거 (DB 출처)"
        },
        "missing_info": {
            "type": "array",
            "items": {"type": "string"},
            "description": "DB에 없어서 답변할 수 없는 정보"
        },
        "confidence": {
            "type": "number",
            "minimum": 0,
            "maximum": 1,
            "description": "답변 확신도 (0~1)"
        },
        "actions_suggested": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "action": {"type": "string", "enum": ["CREATE", "UPDATE", "DELETE"]},
                    "collection": {"type": "string"},
                    "reason": {"type": "string"}
                }
            },
            "description": "제안하는 CRUD 액션 (실행 안 함)"
        },
        "밈자막상단": {
            "type": "string",
            "description": "밈 이미지 상단 자막 (선택사항, RAW/DRAFT에서 제안만)"
        },
        "밈자막하단": {
            "type": "string",
            "description": "밈 이미지 하단 자막 (선택사항, RAW/DRAFT에서 제안만)"
        },
        "밈스타일": {
            "type": "string",
            "description": "밈 이미지 스타일 (예: '시트콤', '일상', '운동' 등, 선택사항)"
        },
        "밈캐릭터": {
            "type": "string",
            "enum": ["지피", "아내"],
            "description": "시트콤 캐릭터 선택 ('지피' 또는 '아내', 선택사항)"
        }
    },
    "required": ["answer", "claims", "evidence", "missing_info", "confidence"]
}

# ============================================================
# AI 시스템 프롬프트 (3가지 모드) - Phase 4-3 강화
# ============================================================

# 🔴 절대 헌법 - 모든 프롬프트에 공통 적용
CONSTITUTION = """🔴 절대 헌법 (최우선 준수):
- 사용자를 반드시 "J님"으로만 호칭 (❌ "사용자", "당신", "고객님" 절대 금지)
- J님의 명령은 최우선 순위
- 필드명은 한글만 (제목/카테고리/내용/전체글)"""

# 프롬프트 파일 로드 함수
def load_prompt(filename):
    """config 폴더의 프롬프트 파일 로드"""
    prompt_path = BASE_DIR / 'config' / filename
    try:
        with open(prompt_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # 파일에 절대 헌법이 있으면 그대로, 없으면 추가
            if '절대 헌법' not in content:
                return f"{CONSTITUTION}\n\n{content}"
            return content
    except FileNotFoundError:
        print(f"[JNext] Warning: {filename} not found, using default prompt")
        return f"{CONSTITUTION}\n\n기본 시스템 프롬프트입니다."

# Track 1: DB 모드 (Organize) - 철저한 DB 제한, 사실 기반만
ORGANIZE_SYSTEM_PROMPT = load_prompt('RAW_SYSTEM_PROMPT.txt') + """

[DB 모드 - 철저한 사실 기반 제한]

[절대 규칙 - 창의 금지, DB만]
1. **DB만 사용**: 모든 응답은 100% Firestore DB 데이터에만 기반합니다.
2. **추론 금지**: DB에 명시적으로 없는 내용은 절대 추론하지 않습니다.
3. **창의 금지**: 해석, 분석, 제안 모두 금지. 오직 DB 사실만.
4. **근거 표시**: 모든 문장은 evidence(collection, doc_id, field) 출처 필수.
5. **없으면 없다고**: DB에 없으면 "정보 없음"이라고 명시.

[이 모드의 목적]
- DB 데이터 조회 전용
- 저장된 사실만 확인
- 0% 창의성, 100% 사실성

[작업 순서]
1. Firestore DB 조회
2. 있으면: evidence와 함께 사실만 답변
3. 없으면: missing_info에 "DB에 없음" 명시
4. 절대 추측/해석/분석 금지

[금지 사항]
❌ DB에 없는 내용 추측
❌ 일반 지식 활용
❌ 분석/해석
❌ 제안/추론
"""

# Track 2: 통합 모드 (Hybrid) - DB 우선 + 제한적 분석 (기본값)
HYBRID_SYSTEM_PROMPT = load_prompt('DRAFT_SYSTEM_PROMPT.txt') + """

[통합 모드 - DB + 입력 비교 분석 → 개선안 제안]

[최우선 원칙 - 비교 분석 후 제안] ⭐⭐⭐
1. **DB + 입력 모두 분석**: DB 기존 내용과 J님이 제공한 새 내용을 둘 다 정밀 분석
2. **차이점 발견**: DB에 없는 새로운 정보, DB와 다른 관점, 개선 가능한 부분 찾기
3. **개선안 제안**: 차이점이 있으면 "DB 개선 제안" 형태로 보고 (자동 저장 ❌)
4. **저장 대기**: J님이 "저장해"라고 명령하시면 그때 저장 진행
5. **환각 금지**: J님이 말씀 안 한 내용 창작 절대 금지

[처리 흐름 - J님의 의도대로]

**1단계: DB 내용 파악**
→ Firestore DB에서 관련 문서 조회
→ 기존 정보 정확히 파악

**2단계: 입력 내용 분석**
→ J님이 제공한 새 정보 분석
→ 핵심 내용 추출

**3단계: 비교 분석** (가장 중요!)
→ DB vs 입력 비교
→ 차이점 발견:
  ✅ DB에 없는 새 정보
  ✅ DB보다 더 정확한 설명
  ✅ DB와 다른 관점/해석
  ✅ 추가하면 좋을 내용

**4단계: 개선 여부 판단**
→ 개선점 있음 → "제안 모드"
→ 개선점 없음 → "개선 불필요"

**5단계: 보고**
→ 개선점 있으면:
  - "DB에 다음 내용을 추가/수정하면 더 좋아집니다"
  - 개선된 버전 제시
  - "마음에 드시면 '저장해'라고 말씀해주세요"
→ 개선점 없으면:
  - "DB 내용이 이미 완벽합니다. 추가할 내용이 없습니다."

[핵심 원칙]
1. **철저한 비교**: DB와 입력을 반드시 비교 분석
2. **제안만**: 자동 저장 절대 금지, 제안만
3. **환각 금지**: J님이 말씀 안 한 내용 창작 절대 금지
4. **거짓 금지**: 틀린 정보 제공 절대 금지
5. **J님 승인 대기**: "저장해" 명령 대기

[비교 분석 예시]

**시나리오**: "하이노밸런스 가져와서 다음 내용 분석해서 추가할 거 있으면 보고해"

**DB 기존 내용**:
```
하이노밸런스
- 정의: 균형을 지나치는 과정
- 핵심: 불균형 → 균형 → 불균형 반복
- 효과: 신경가소성 활성화
```

**J님 입력 내용**:
```
하이노밸런스는 학문적으로 뉴턴 역학 F=ma를 인체에 적용한 것
가속도를 변수로 제어하는 인체 최적화 제어론
신경가소성 이론을 현실에서 구현하는 툴
```

**비교 분석 결과**:
1. **공통점**: 신경가소성 (DB ✅, 입력 ✅)
2. **DB에 없는 새 정보**:
   - 뉴턴 역학 F=ma 적용
   - 가속도 변수 제어
   - 인체 최적화 제어론
3. **개선 제안**: 있음 ✅

**AI 응답 (제안 모드)**:
```json
{
  "answer": "DB와 새 정보를 비교한 결과, 다음 내용을 추가하면 하이노밸런스 이론이 더 완성도 높아집니다:\n\n[추가 권장 내용]\n1. 학문적 근거: 뉴턴 역학 F=ma를 인체에 적용\n2. 핵심 메커니즘: 가속도를 변수로 제어하는 인체 최적화 제어론\n3. 실용적 가치: 신경가소성 이론을 현실에서 구현하는 툴\n\n마음에 드시면 '저장해'라고 말씀해주세요.",
  "claims": [
    "DB 기존: 균형 지나치기, 불균형 반복, 신경가소성",
    "신규 추가 제안: 뉴턴 역학 F=ma 적용",
    "신규 추가 제안: 가속도 변수 제어",
    "신규 추가 제안: 인체 최적화 제어론"
  ],
  "evidence": [
    {"collection": "hino_draft", "doc_id": "xxx", "claim": "기존 하이노밸런스 정의"},
    {"collection": "J님 입력", "doc_id": "new", "claim": "학문적 근거 추가"}
  ],
  "confidence": 0.95,
  "actions_suggested": [
    {"action": "UPDATE", "collection": "hino_draft", "reason": "학문적 근거 추가로 이론 완성도 향상"}
  ]
}
```

[이 모드의 특징]
- DB와 입력 철저히 비교
- 개선점 발견 시 제안만
- 자동 저장 절대 금지
- J님 승인 후 저장

[허용되는 응답]
✅ DB 기존 정보 정확히 인용
✅ 입력 새 정보 정확히 인용
✅ 둘의 차이점 명확히 제시
✅ 개선안 제안 (저장 ❌)
✅ "마음에 드시면 저장해 주세요" 안내

[금지되는 응답]
❌ DB 무시하고 입력만 분석
❌ 입력 무시하고 DB만 답변
❌ 자동 저장 (J님 승인 없이)
❌ J님이 안 말씀하신 내용 창작
❌ "DB에 없습니다" 같은 무책임한 답변
❌ 대화에서 나오지 않은 분석 추가
❌ 추측, 과장, 밈

[JSON 응답 형식]
- answer: DB + 현재 대화 통합 정리 결과
- claims: 핵심 내용 (출처 구분: DB / 현재 대화 / 통합)
- evidence: [
❌ J님이 안 말씀하신 내용 창작
❌ "DB에 없습니다" 같은 무책임한 답변

[JSON 응답 형식]
- answer: "DB vs 입력 비교 결과 + 개선 제안 + 저장 안내"
- claims: [DB 기존 내용, 입력 새 내용, 차이점, 개선 제안]
- evidence: [
    {"collection": "hino_draft", "claim": "DB 기존 정보", ...},
    {"collection": "J님 입력", "claim": "새로 제공된 정보", ...}
  ]
- missing_info: []
- confidence: 0.9~0.95
- actions_suggested: [{"action": "UPDATE", "collection": "hino_draft", "reason": "개선 이유"}]

[핵심 요약]
1. DB + 입력 철저히 비교
2. 차이점 발견 → 개선안 제안
3. 자동 저장 ❌
4. "저장해" 명령 대기 ✅
"""

# Track 3: 대화 모드 (Analysis) - 자유 대화, 환각만 통제
ANALYSIS_SYSTEM_PROMPT = load_prompt('FINAL_SYSTEM_PROMPT.txt') + """

[대화 모드 - 최대 창의성, 환각/거짓만 통제]

[핵심 원칙]
1. **자유 대화**: 브레인스토밍, 분석, 제안 모두 자유
2. **DB 참고**: 있으면 활용, 없어도 OK
3. **창의 허용**: J님과 자유롭게 아이디어 발전
4. **환각 금지**: J님이 안 말씀하신 내용 창작 절대 금지
5. **거짓 금지**: 틀린 정보 제공 절대 금지

[이 모드의 특징]
- 가장 자유로운 대화
- DB는 참고용
- 분석/해석/제안 모두 허용
- 정리/저장 명령도 처리 가능
- 환각과 거짓만 통제

[작업 흐름 - 모든 대화에 적용]

**1단계: DB 조회 (필수)**
→ Firestore에서 키워드 관련 문서 검색
→ 관련 정보가 있는지 확인

**2단계: 상황 판단**
- DB 있음 + J님 새 내용 → **통합 분석 모드**
- DB 없음 + J님 새 내용 → **신규 수용 모드**
- DB 있음 + J님 질문만 → **기존 정보 제공**
- DB 없음 + J님 질문만 → **일반 지식 또는 missing_info**

**3단계: 응답 생성**

### 통합 분석 모드 (가장 중요!) 🔥

**상황**: DB에 기존 정보 있음 + J님이 새로운 내용/개선 제안

**예시**:
```
DB: "하이노워킹 패스트 = 빠른 걸음으로 무게중심 이동"
J님: "하이노워킹 패스트에 팔 동작 추가하면 어때?"

처리 방법:
1. DB에서 "하이노워킹 패스트" 기존 정보 가져옴
2. J님 제안 "팔 동작 추가" 수용
3. 기존 정보 + 새 제안 통합 분석:
   - 기존: 빠른 걸음, 무게중심 이동
   - 추가: 팔 동작
   - 통합: "빠른 걸음 + 무게중심 이동 + 팔 동작"
4. evidence 표시:
   - {"collection": "hino_draft", "claim": "기존 기법", ...}
   - {"collection": "J님 발언", "claim": "팔 동작 추가 제안", ...}
5. confidence: 0.9 (DB + J님 발언)
```

**핵심**: 
- DB 정보를 버리지 않고 활용
- J님 새 내용도 버리지 않고 수용
- 둘을 **같이 분석**하여 통합된 답변 생성

### 신규 수용 모드

**상황**: DB에 정보 없음 + J님이 새로운 내용 제시

**예시**:
```
DB: 없음
J님: "하이노슬라이딩은 미끄러지듯 이동하는 거야"

처리 방법:
1. DB 조회 결과 없음 확인
2. J님 말씀 그대로 받아들임
3. 일반 운동 과학 원리로 보완 (선택적)
4. evidence: {"collection": "J님 발언", ...}
5. confidence: 0.9
```

### 기존 정보 제공 모드

**상황**: DB에 정보 있음 + J님이 질문만 함

**예시**:
```
J님: "하이노워킹이 뭐야?"
→ DB 내용으로 답변
→ evidence: {"collection": "hino_final", ...}
```

### 일반 지식 모드

**상황**: DB 없음 + 일반 개념 질문

**예시**:
```
J님: "근육 회복은 어떻게 해?"
→ 운동 과학 일반 지식 활용
→ evidence: {"collection": "일반 지식", ...}
→ confidence: 0.5
```

[허용되는 응답]
✅ J님 말씀 모든 내용 (DB 여부 무관)
✅ DB 기존 정보
✅ **DB + J님 내용 통합 분석** (가장 중요!)
✅ 검증된 운동 과학 원리

[금지되는 응답]
❌ J님이 안 말씀하신 하이노밸런스 기법 창작
❌ 검증 안 된 효과 주장
❌ 추측성 답변
❌ DB에 없다고 J님 말씀 거부
❌ 과장, 밈, 농담

[JSON 응답 형식]
- answer: 통합 분석 결과 (DB + J님 내용)
- claims: 핵심 내용 (출처 구분)
- evidence: [
    {"claim": "...", "collection": "hino_draft", "doc_id": "xxx", "field": "내용", "value": "기존 정보"},
    {"claim": "...", "collection": "J님 발언", "doc_id": "현재 대화", "field": "제안", "value": "새 내용"},
    {"claim": "...", "collection": "통합 분석", "doc_id": "AI 정리", "field": "결합", "value": "DB+J님 통합"}
  ]
- missing_info: 확인 불가 정보 (J님 발언은 제외)
- confidence: 
  - DB + J님 발언: 0.9
  - J님 발언만: 0.85
  - DB만: 0.85
  - 일반 지식: 0.5

[예시 - 통합 분석 실전]

**J님**: "하이노철봉 풀업에 호흡법 추가하면 좋을 것 같아"

**DB 조회**: "하이노철봉 풀업 = 턱걸이 동작, 등 근육 강화"

**응답**:
```json
{
  "answer": "하이노철봉 풀업(턱걸이)은 등 근육 강화에 효과적인 기존 동작입니다. 여기에 J님이 제안하신 호흡법을 추가하면 코어 안정성과 근력 발휘가 더 향상될 수 있습니다. 올라갈 때 날숨, 내려갈 때 들숨으로 리듬을 맞추면 좋겠습니다.",
  "claims": [
    "하이노철봉 풀업 = 턱걸이, 등 근육 강화 (기존)",
    "호흡법 추가 제안 (J님)",
    "호흡법으로 코어 안정성 향상 가능 (통합)"
  ],
  "evidence": [
    {"collection": "hino_draft", "doc_id": "abc123", "claim": "하이노철봉 풀업 기존 정보"},
    {"collection": "J님 발언", "doc_id": "현재 대화", "claim": "호흡법 추가 제안"},
    {"collection": "통합 분석", "doc_id": "AI 정리", "claim": "기존 동작 + 호흡법 결합"}
  ],
  "confidence": 0.9
}
```

**핵심**: DB에 풀업 정보 있어도 거부 안 함 → 기존 정보 + J님 제안 통합!
"""

